version: '3.9'

networks:
  default:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: alankrantas.github.io
    restart: always
    ports:
      - '8080:80'
    networks:
      - default
    extra_hosts:
      - 'host.docker.internal:host-gateway'
