name: Build and Deployment CICD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      BUILD_TIME: ''
      BUILD_MESSAGE: ''

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm i -g yarn
          yarn install --frozen-lockfile

      - name: Build Production
        run: |
          yarn check
          yarn build

      - name: Set Build Time
        run: echo "BUILD_TIME = $(date +'%Y-%m-%d %H:%M')"

      - name: Set Commit Message (If Push)
        if: ${{ github.event_name == 'push' }}
        run: echo "BUILD_MESSAGE = ${{ github.event.head_commit.message }}"

      - name: Set Commit Message (If Pull Request)
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "BUILD_MESSAGE = ${{ github.event.pull_request.body }}"

      - name: Set Commit Message (If Workflow Dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "BUILD_MESSAGE = "manual workflow dispatch"

      - name: Write Commit Message to build.json
        run: |
          echo "{ \"build_time\": \"$BUILD_TIME\", \"build_message\": \"$BUILD_MESSAGE\" }" | jq '.' > ./build/build.json

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build'

  Deploy:
    runs-on: ubuntu-latest
    needs: Build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
